version: '3.8'

services:
  # Laravel Backend
  app:
    build: .
    container_name: laravel_app
    working_dir: /var/www/html
    volumes:
      - ./app:/var/www/html
    networks:
      - laravel_network
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_DATABASE=laravel
      - DB_USERNAME=root
      - DB_PASSWORD=root

  # Nginx (Web Server)
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt/live:/etc/letsencrypt/live
    ports:
      - "80:80"
      - "443:443"
    networks:
      - laravel_network
    depends_on:
      - app

  # MySQL Database
  db:
    image: mysql:5.7
    container_name: mysql
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=laravel
    networks:
      - laravel_network

  # Node.js (Vue.js)
  node:
    image: node:22-alpine
    container_name: node
    working_dir: /var/www/html
    volumes:
      - ./frontend:/var/www/html
    networks:
      - laravel_network
    command: npm run serve
    depends_on:
      - app
    ports:
      - "8080:8080"

networks:
  laravel_network:
    driver: bridge

volumes:
  db_data:
    driver: local

